name: Oasis

description: Oasis app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/estandarte_oasis.png
    - assets/imgs/logo_oasis.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/only-logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/imgs/only-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/imgs/only-logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/imgs/only-logo.png"

